build:
  nodes:
    analysis:
      dependencies:
        override:
          - composer self-update --2
          - composer install --no-interaction --no-scripts
      tests:
        override:
          - php-scrutinizer-run

checks: 
  php: true

coding_style: 
  php: 
    spaces: 
      around_operators: 
        concatenation: true
      before_parentheses:
        closure_definition: true


filter:
  paths:
    - src/
