build:
  environment:
    # For some reasons Composer version depends on PHP version
    # so we need a version of PHP high enough to get Composer2.
    php: 7.4.27
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks: 
  php: true

coding_style: 
  php: 
    spaces: 
      around_operators: 
        concatenation: true
      before_parentheses:
        closure_definition: true


filter:
  paths:
    - src/
