build:
  environment:
    php: 7.4.27
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks: 
  php: true

coding_style: 
  php: 
    spaces: 
      around_operators: 
        concatenation: true
      before_parentheses:
        closure_definition: true


filter:
  paths:
    - src/
