build:
  nodes:
    analysis:
      dependencies:
        before:
          - curl -sL https://getcomposer.org/download/latest-stable/composer.phar -o /usr/local/bin/composer
      tests:
        override:
          - php-scrutinizer-run

checks: 
  php: true

coding_style: 
  php: 
    spaces: 
      around_operators: 
        concatenation: true
      before_parentheses:
        closure_definition: true


filter:
  paths:
    - src/
