build:
  nodes:
    analysis:
      dependencies:
        before:
          - /home/scrutinizer/.phpenv/shims/php /usr/bin/composer.phar self-update --2 --no-interaction
      tests:
        override:
          - php-scrutinizer-run

checks: 
  php: true

coding_style: 
  php: 
    spaces: 
      around_operators: 
        concatenation: true
      before_parentheses:
        closure_definition: true


filter:
  paths:
    - src/
