#!/usr/bin/env php
<?php

require_once(__DIR__ . '/bootstrap.php');

use Churn\Commands\ChurnCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new ChurnCommand);
$application->run();
