name: "Pull Request"

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'img/**'

jobs:
  mutation:
    name: "Mutation testing"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          ini-values: "error_reporting=-1, display_errors=On, display_startup_errors=On, zend.assertions=1"
          php-version: "8.2"
          tools: composer:v2, infection

      - uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          composer-options: "--no-scripts"

      - name: "Run Infection"
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          infection -j$(nproc) --logger-github --show-mutations --only-covered --git-diff-filter=AM --git-diff-base=origin/$GITHUB_BASE_REF --ignore-msi-with-no-mutations --min-msi=75 --min-covered-msi=80
